(lang dune 3.23)

(name assembler)

(generate_opam_files true)

(source
 (github Auburger/Overture-Assembler))

(authors "Aubrie Chan <aubriechan07@gmail.com>")

(license LICENSE)

(documentation https://url/to/documentation)

(package
 (name assembler)
 (synopsis "An assembler for the OVERTURE ISA from the game Turing Complete")
 (description "A longer description")
 (depends ocaml)
 (tags
  ("add topics" "to describe" your project)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
